import { VIPTier, CoinType, Game, GameType } from '@/types';

// ============================================================
// VIP Tiers
// ============================================================

export const VIP_TIERS: VIPTier[] = [
  {
    level: 0,
    name: 'None',
    color: '#557086',
    icon: '👤',
    min_wager: 0,
    rakeback_percent: 0,
    level_up_bonus: 0,
    weekly_bonus: 0,
    monthly_bonus: 0,
    features: [],
  },
  {
    level: 1,
    name: 'Bronze I',
    color: '#b45309',
    icon: '🥉',
    min_wager: 10000,
    rakeback_percent: 5,
    level_up_bonus: 25,
    weekly_bonus: 10,
    monthly_bonus: 50,
    features: ['Basic rakeback', 'Weekly bonuses'],
  },
  {
    level: 2,
    name: 'Bronze II',
    color: '#b45309',
    icon: '🥉',
    min_wager: 50000,
    rakeback_percent: 6,
    level_up_bonus: 50,
    weekly_bonus: 25,
    monthly_bonus: 100,
    features: ['Increased rakeback', 'Priority support'],
  },
  {
    level: 3,
    name: 'Bronze III',
    color: '#b45309',
    icon: '🥉',
    min_wager: 100000,
    rakeback_percent: 7,
    level_up_bonus: 100,
    weekly_bonus: 50,
    monthly_bonus: 200,
    features: ['Enhanced rakeback', 'Custom avatar frame'],
  },
  {
    level: 4,
    name: 'Silver I',
    color: '#9ca3af',
    icon: '🥈',
    min_wager: 250000,
    rakeback_percent: 8,
    level_up_bonus: 200,
    weekly_bonus: 100,
    monthly_bonus: 400,
    features: ['Silver rakeback', 'Daily reload bonus'],
  },
  {
    level: 5,
    name: 'Silver II',
    color: '#9ca3af',
    icon: '🥈',
    min_wager: 500000,
    rakeback_percent: 9,
    level_up_bonus: 400,
    weekly_bonus: 200,
    monthly_bonus: 800,
    features: ['Enhanced reload', 'VIP chat room'],
  },
  {
    level: 6,
    name: 'Silver III',
    color: '#9ca3af',
    icon: '🥈',
    min_wager: 1000000,
    rakeback_percent: 10,
    level_up_bonus: 800,
    weekly_bonus: 400,
    monthly_bonus: 1500,
    features: ['Premium reload', 'Exclusive promotions'],
  },
  {
    level: 7,
    name: 'Gold I',
    color: '#f59e0b',
    icon: '🏆',
    min_wager: 2500000,
    rakeback_percent: 12,
    level_up_bonus: 1500,
    weekly_bonus: 800,
    monthly_bonus: 3000,
    features: ['Gold rakeback', 'Personal account manager'],
  },
  {
    level: 8,
    name: 'Gold II',
    color: '#f59e0b',
    icon: '🏆',
    min_wager: 5000000,
    rakeback_percent: 14,
    level_up_bonus: 3000,
    weekly_bonus: 1500,
    monthly_bonus: 6000,
    features: ['Enhanced VIP support', 'Increased limits'],
  },
  {
    level: 9,
    name: 'Gold III',
    color: '#f59e0b',
    icon: '🏆',
    min_wager: 10000000,
    rakeback_percent: 16,
    level_up_bonus: 5000,
    weekly_bonus: 3000,
    monthly_bonus: 12000,
    features: ['Top-tier support', 'Exclusive events'],
  },
  {
    level: 10,
    name: 'Platinum I',
    color: '#22d3ee',
    icon: '💎',
    min_wager: 25000000,
    rakeback_percent: 18,
    level_up_bonus: 10000,
    weekly_bonus: 5000,
    monthly_bonus: 25000,
    features: ['Platinum perks', 'Custom promotions', 'Luxury gifts'],
  },
  {
    level: 11,
    name: 'Platinum II',
    color: '#22d3ee',
    icon: '💎',
    min_wager: 50000000,
    rakeback_percent: 20,
    level_up_bonus: 20000,
    weekly_bonus: 10000,
    monthly_bonus: 50000,
    features: ['Premium VIP', 'Travel packages', 'Dedicated host'],
  },
  {
    level: 12,
    name: 'Diamond',
    color: '#6366f1',
    icon: '👑',
    min_wager: 100000000,
    rakeback_percent: 25,
    level_up_bonus: 50000,
    weekly_bonus: 25000,
    monthly_bonus: 100000,
    features: ['Maximum rakeback', 'All perks unlocked', 'Diamond-only events', 'Bespoke rewards'],
  },
];

// ============================================================
// Supported Coins
// ============================================================

export interface CoinInfo {
  symbol: CoinType;
  name: string;
  icon: string;
  color: string;
  decimals: number;
  networks: string[];
  minDeposit: number;
  minWithdraw: number;
  withdrawFee: number;
}

export const SUPPORTED_COINS: CoinInfo[] = [
  { symbol: 'BTC', name: 'Bitcoin', icon: '₿', color: '#f7931a', decimals: 8, networks: ['Bitcoin', 'Lightning'], minDeposit: 0.0001, minWithdraw: 0.0005, withdrawFee: 0.00005 },
  { symbol: 'ETH', name: 'Ethereum', icon: 'Ξ', color: '#627eea', decimals: 18, networks: ['Ethereum', 'Arbitrum', 'Optimism'], minDeposit: 0.001, minWithdraw: 0.005, withdrawFee: 0.001 },
  { symbol: 'USDT', name: 'Tether', icon: '₮', color: '#26a17b', decimals: 6, networks: ['Ethereum', 'Tron', 'BSC', 'Polygon'], minDeposit: 1, minWithdraw: 10, withdrawFee: 1 },
  { symbol: 'USDC', name: 'USD Coin', icon: '$', color: '#2775ca', decimals: 6, networks: ['Ethereum', 'Polygon', 'Arbitrum'], minDeposit: 1, minWithdraw: 10, withdrawFee: 1 },
  { symbol: 'BNB', name: 'BNB', icon: '◆', color: '#f3ba2f', decimals: 18, networks: ['BSC'], minDeposit: 0.01, minWithdraw: 0.05, withdrawFee: 0.005 },
  { symbol: 'SOL', name: 'Solana', icon: '◎', color: '#9945ff', decimals: 9, networks: ['Solana'], minDeposit: 0.1, minWithdraw: 0.5, withdrawFee: 0.01 },
  { symbol: 'DOGE', name: 'Dogecoin', icon: 'Ð', color: '#c2a633', decimals: 8, networks: ['Dogecoin'], minDeposit: 10, minWithdraw: 50, withdrawFee: 5 },
  { symbol: 'TRX', name: 'TRON', icon: '⟐', color: '#ff0013', decimals: 6, networks: ['Tron'], minDeposit: 10, minWithdraw: 50, withdrawFee: 1 },
  { symbol: 'LTC', name: 'Litecoin', icon: 'Ł', color: '#bfbbbb', decimals: 8, networks: ['Litecoin'], minDeposit: 0.01, minWithdraw: 0.1, withdrawFee: 0.001 },
  { symbol: 'XRP', name: 'Ripple', icon: '✕', color: '#23292f', decimals: 6, networks: ['Ripple'], minDeposit: 1, minWithdraw: 10, withdrawFee: 0.25 },
  { symbol: 'ADA', name: 'Cardano', icon: '₳', color: '#0d1e30', decimals: 6, networks: ['Cardano'], minDeposit: 5, minWithdraw: 10, withdrawFee: 1 },
  { symbol: 'MATIC', name: 'Polygon', icon: '⬡', color: '#8247e5', decimals: 18, networks: ['Polygon'], minDeposit: 1, minWithdraw: 10, withdrawFee: 0.1 },
];

// ============================================================
// Game List
// ============================================================

export const GAMES: Game[] = [
  {
    id: 'dice-001',
    name: 'Classic Dice',
    slug: 'dice',
    type: GameType.DICE,
    provider: 'Bb.GAME Originals',
    thumbnail: '/games/dice.jpg',
    description: 'Roll the dice and predict whether the result will be over or under your target number.',
    house_edge: 1,
    min_bet: 0.00001,
    max_bet: 100,
    max_multiplier: 9900,
    is_active: true,
    is_featured: true,
    is_new: false,
    is_hot: true,
    play_count: 1250000,
    category: 'originals',
    tags: ['dice', 'original', 'provably-fair'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'crash-001',
    name: 'Crash',
    slug: 'crash',
    type: GameType.CRASH,
    provider: 'Bb.GAME Originals',
    thumbnail: '/games/crash.jpg',
    description: 'Watch the multiplier climb and cash out before it crashes!',
    house_edge: 1,
    min_bet: 0.00001,
    max_bet: 100,
    max_multiplier: 1000000,
    is_active: true,
    is_featured: true,
    is_new: false,
    is_hot: true,
    play_count: 2100000,
    category: 'originals',
    tags: ['crash', 'original', 'multiplayer', 'provably-fair'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'plinko-001',
    name: 'Plinko',
    slug: 'plinko',
    type: GameType.PLINKO,
    provider: 'Bb.GAME Originals',
    thumbnail: '/games/plinko.jpg',
    description: 'Drop the ball and watch it bounce through pegs to land on a multiplier.',
    house_edge: 1,
    min_bet: 0.00001,
    max_bet: 100,
    max_multiplier: 1000,
    is_active: true,
    is_featured: true,
    is_new: false,
    is_hot: true,
    play_count: 890000,
    category: 'originals',
    tags: ['plinko', 'original', 'provably-fair'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'mines-001',
    name: 'Mines',
    slug: 'mines',
    type: GameType.MINES,
    provider: 'Bb.GAME Originals',
    thumbnail: '/games/mines.jpg',
    description: 'Reveal gems and avoid mines. The more gems you find, the higher your payout.',
    house_edge: 1,
    min_bet: 0.00001,
    max_bet: 100,
    max_multiplier: 24.75,
    is_active: true,
    is_featured: true,
    is_new: false,
    is_hot: true,
    play_count: 1450000,
    category: 'originals',
    tags: ['mines', 'original', 'provably-fair'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'tower-001',
    name: 'Tower',
    slug: 'tower',
    type: GameType.TOWER,
    provider: 'Bb.GAME Originals',
    thumbnail: '/games/tower.jpg',
    description: 'Climb the tower by choosing the correct tiles on each level.',
    house_edge: 1,
    min_bet: 0.00001,
    max_bet: 100,
    max_multiplier: 500,
    is_active: true,
    is_featured: false,
    is_new: true,
    is_hot: false,
    play_count: 340000,
    category: 'originals',
    tags: ['tower', 'original', 'provably-fair'],
    created_at: '2024-06-01T00:00:00Z',
  },
  {
    id: 'limbo-001',
    name: 'Limbo',
    slug: 'limbo',
    type: GameType.LIMBO,
    provider: 'Bb.GAME Originals',
    thumbnail: '/games/limbo.jpg',
    description: 'Set your target multiplier and see if the result goes higher.',
    house_edge: 1,
    min_bet: 0.00001,
    max_bet: 100,
    max_multiplier: 1000000,
    is_active: true,
    is_featured: false,
    is_new: false,
    is_hot: false,
    play_count: 560000,
    category: 'originals',
    tags: ['limbo', 'original', 'provably-fair'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'hilo-001',
    name: 'HiLo',
    slug: 'hilo',
    type: GameType.HILO,
    provider: 'Bb.GAME Originals',
    thumbnail: '/games/hilo.jpg',
    description: 'Predict whether the next card will be higher or lower.',
    house_edge: 1,
    min_bet: 0.00001,
    max_bet: 100,
    max_multiplier: 100,
    is_active: true,
    is_featured: false,
    is_new: false,
    is_hot: false,
    play_count: 410000,
    category: 'originals',
    tags: ['hilo', 'original', 'provably-fair', 'cards'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'keno-001',
    name: 'Keno',
    slug: 'keno',
    type: GameType.KENO,
    provider: 'Bb.GAME Originals',
    thumbnail: '/games/keno.jpg',
    description: 'Pick your numbers and see how many match the draw.',
    house_edge: 1,
    min_bet: 0.00001,
    max_bet: 100,
    max_multiplier: 10000,
    is_active: true,
    is_featured: false,
    is_new: false,
    is_hot: false,
    play_count: 290000,
    category: 'originals',
    tags: ['keno', 'original', 'provably-fair'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'coinflip-001',
    name: 'Coin Flip',
    slug: 'coinflip',
    type: GameType.COINFLIP,
    provider: 'Bb.GAME Originals',
    thumbnail: '/games/coinflip.jpg',
    description: 'Call heads or tails. Simple, fast, and exciting.',
    house_edge: 1,
    min_bet: 0.00001,
    max_bet: 100,
    max_multiplier: 1.98,
    is_active: true,
    is_featured: false,
    is_new: true,
    is_hot: false,
    play_count: 680000,
    category: 'originals',
    tags: ['coinflip', 'original', 'provably-fair'],
    created_at: '2024-09-01T00:00:00Z',
  },
  {
    id: 'wheel-001',
    name: 'Wheel of Fortune',
    slug: 'wheel',
    type: GameType.WHEEL,
    provider: 'Bb.GAME Originals',
    thumbnail: '/games/wheel.jpg',
    description: 'Spin the wheel and land on big multipliers.',
    house_edge: 2,
    min_bet: 0.00001,
    max_bet: 100,
    max_multiplier: 49.5,
    is_active: true,
    is_featured: false,
    is_new: false,
    is_hot: false,
    play_count: 520000,
    category: 'originals',
    tags: ['wheel', 'original', 'provably-fair'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'roulette-001',
    name: 'European Roulette',
    slug: 'roulette',
    type: GameType.ROULETTE,
    provider: 'Evolution Gaming',
    thumbnail: '/games/roulette.jpg',
    description: 'Classic European Roulette with live dealer.',
    house_edge: 2.7,
    min_bet: 0.001,
    max_bet: 50,
    max_multiplier: 36,
    is_active: true,
    is_featured: true,
    is_new: false,
    is_hot: true,
    play_count: 980000,
    category: 'live',
    tags: ['roulette', 'live', 'table'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'blackjack-001',
    name: 'Blackjack VIP',
    slug: 'blackjack',
    type: GameType.BLACKJACK,
    provider: 'Evolution Gaming',
    thumbnail: '/games/blackjack.jpg',
    description: 'Beat the dealer without going over 21.',
    house_edge: 0.5,
    min_bet: 0.001,
    max_bet: 50,
    max_multiplier: 3,
    is_active: true,
    is_featured: true,
    is_new: false,
    is_hot: false,
    play_count: 720000,
    category: 'live',
    tags: ['blackjack', 'live', 'table', 'cards'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'baccarat-001',
    name: 'Speed Baccarat',
    slug: 'baccarat',
    type: GameType.BACCARAT,
    provider: 'Pragmatic Play',
    thumbnail: '/games/baccarat.jpg',
    description: 'Fast-paced baccarat with lightning rounds.',
    house_edge: 1.06,
    min_bet: 0.001,
    max_bet: 50,
    max_multiplier: 11,
    is_active: true,
    is_featured: false,
    is_new: false,
    is_hot: false,
    play_count: 450000,
    category: 'live',
    tags: ['baccarat', 'live', 'table', 'cards'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'slots-001',
    name: 'Gates of Olympus',
    slug: 'gates-of-olympus',
    type: GameType.SLOTS,
    provider: 'Pragmatic Play',
    thumbnail: '/games/wheel.jpg',
    description: 'Zeus drops multiplier symbols for huge wins.',
    house_edge: 3.5,
    min_bet: 0.001,
    max_bet: 50,
    max_multiplier: 5000,
    is_active: true,
    is_featured: true,
    is_new: false,
    is_hot: true,
    play_count: 3200000,
    category: 'slots',
    tags: ['slots', 'popular', 'high-volatility'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'slots-002',
    name: 'Sweet Bonanza',
    slug: 'sweet-bonanza',
    type: GameType.SLOTS,
    provider: 'Pragmatic Play',
    thumbnail: '/games/coinflip.jpg',
    description: 'Tumbling wins with increasing multipliers.',
    house_edge: 3.49,
    min_bet: 0.001,
    max_bet: 50,
    max_multiplier: 21175,
    is_active: true,
    is_featured: true,
    is_new: false,
    is_hot: true,
    play_count: 2800000,
    category: 'slots',
    tags: ['slots', 'popular', 'high-volatility'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'slots-003',
    name: 'Starlight Princess',
    slug: 'starlight-princess',
    type: GameType.SLOTS,
    provider: 'Pragmatic Play',
    thumbnail: '/games/limbo.jpg',
    description: 'Magical princess grants free spins and multipliers.',
    house_edge: 3.53,
    min_bet: 0.001,
    max_bet: 50,
    max_multiplier: 5000,
    is_active: true,
    is_featured: false,
    is_new: false,
    is_hot: true,
    play_count: 1900000,
    category: 'slots',
    tags: ['slots', 'popular', 'high-volatility'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'slots-004',
    name: 'Sugar Rush',
    slug: 'sugar-rush',
    type: GameType.SLOTS,
    provider: 'Pragmatic Play',
    thumbnail: '/games/plinko.jpg',
    description: 'Cluster pays with growing multiplier positions.',
    house_edge: 3.5,
    min_bet: 0.001,
    max_bet: 50,
    max_multiplier: 5000,
    is_active: true,
    is_featured: false,
    is_new: true,
    is_hot: false,
    play_count: 750000,
    category: 'slots',
    tags: ['slots', 'new'],
    created_at: '2024-08-01T00:00:00Z',
  },
  {
    id: 'video-poker-001',
    name: 'Jacks or Better',
    slug: 'jacks-or-better',
    type: GameType.VIDEO_POKER,
    provider: 'Bb.GAME Originals',
    thumbnail: '/games/hilo.jpg',
    description: 'Classic video poker. Get a pair of Jacks or better to win.',
    house_edge: 0.46,
    min_bet: 0.0001,
    max_bet: 10,
    max_multiplier: 800,
    is_active: true,
    is_featured: false,
    is_new: false,
    is_hot: false,
    play_count: 380000,
    category: 'table',
    tags: ['poker', 'cards', 'table'],
    created_at: '2024-01-01T00:00:00Z',
  },
];

// ============================================================
// Game Categories
// ============================================================

export const GAME_CATEGORIES = [
  { id: 'all', label: 'All Games', icon: '🎮' },
  { id: 'originals', label: 'Originals', icon: '⭐' },
  { id: 'slots', label: 'Slots', icon: '🎰' },
  { id: 'live', label: 'Live Casino', icon: '🎥' },
  { id: 'table', label: 'Table Games', icon: '🃏' },
];

// ============================================================
// House Edges
// ============================================================

export const HOUSE_EDGES: Record<string, number> = {
  [GameType.DICE]: 1,
  [GameType.CRASH]: 1,
  [GameType.PLINKO]: 1,
  [GameType.MINES]: 1,
  [GameType.TOWER]: 1,
  [GameType.LIMBO]: 1,
  [GameType.HILO]: 1,
  [GameType.KENO]: 1,
  [GameType.COINFLIP]: 1,
  [GameType.WHEEL]: 2,
  [GameType.ROULETTE]: 2.7,
  [GameType.BLACKJACK]: 0.5,
  [GameType.BACCARAT]: 1.06,
  [GameType.SLOTS]: 3.5,
  [GameType.VIDEO_POKER]: 0.46,
};

// ============================================================
// Sidebar Navigation
// ============================================================

export const SIDEBAR_NAV = {
  casino: [
    { id: 'home', label: 'Home', href: '/', icon: 'Home' },
    { id: 'originals', label: 'Originals', href: '/games/originals', icon: 'Star' },
    { id: 'slots', label: 'Slots', href: '/games/slots', icon: 'Cherry' },
    { id: 'live', label: 'Live Casino', href: '/games/live', icon: 'Video' },
  ],
  sports: [
    { id: 'sports', label: 'Sports', href: '/sports', icon: 'Trophy' },
    { id: 'esports', label: 'Esports', href: '/esports', icon: 'Gamepad2' },
  ],
  promotions: [
    { id: 'promotions', label: 'Promotions', href: '/promotions', icon: 'Gift' },
    { id: 'vip', label: 'VIP Club', href: '/vip', icon: 'Crown' },
    { id: 'affiliate', label: 'Affiliate', href: '/affiliate', icon: 'Users' },
  ],
};

// ============================================================
// App Constants
// ============================================================

export const APP_NAME = 'Bb.GAME';
export const APP_DESCRIPTION = 'The Best Crypto Casino - Play with Bitcoin, Ethereum, and more';
export const APP_URL = process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000';

export const DEFAULT_COIN: CoinType = 'BTC';
export const DEFAULT_BET_AMOUNT = 0.00001;
export const MAX_CHAT_MESSAGES = 100;
export const CHAT_ROOMS = ['english', 'español', 'português', 'türkçe', '中文', 'العربية'];

export const GRADIENT_COLORS = {
  green: 'from-[#00e701] to-[#00b801]',
  purple: 'from-[#6366f1] to-[#8b5cf6]',
  gold: 'from-[#f59e0b] to-[#fbbf24]',
  red: 'from-[#ef4444] to-[#dc2626]',
  blue: 'from-[#3b82f6] to-[#2563eb]',
  cyan: 'from-[#06b6d4] to-[#0891b2]',
  pink: 'from-[#ec4899] to-[#db2777]',
};

// Aliases for compatibility
export const COINS = SUPPORTED_COINS;
export const GAMES_CATALOG = GAMES;
